import { XSourceType } from '../../types';
import type { XSource } from '../types';

export const EXCHANGE_AND_BROKER_X_SOURCES: XSource[] = [
    {
        handle: 'RobinhoodApp',
        displayName: 'Robinhood',
        enabled: true,
        sourceType: XSourceType.BROKER,
        credibilityScore: 95,
        priority: 'P0',
        pollingInterval: 60, // 1m
        categories: ['CRYPTO', 'MEMECOIN'],
        watchTopics: [
            'listing',
            'crypto',
            'meme',
            'Dogecoin',
            'SHIB',
            'PEPE',
            'BONK',
            'WIF',
            'token',
            'new asset',
            'trading support',
        ],
        requiresConfirmation: false,
        officialDomain: 'robinhood.com',
        rsshubRoute: '/twitter/user/RobinhoodApp',
    },
    {
        handle: 'RobinhoodApp_EU',
        displayName: 'Robinhood EU Crypto',
        enabled: true,
        sourceType: XSourceType.BROKER,
        credibilityScore: 95,
        priority: 'P0',
        pollingInterval: 60, // 1m
        categories: ['CRYPTO', 'MEMECOIN'],
        regions: ['EU'],
        watchTopics: ['listing', 'crypto', 'meme', 'token', 'trading support', 'EU'],
        requiresConfirmation: false,
        officialDomain: 'robinhood.com',
        rsshubRoute: '/twitter/user/RobinhoodApp_EU',
    },
    {
        handle: 'CoinbaseMarkets',
        displayName: 'Coinbase Markets',
        enabled: true,
        sourceType: XSourceType.EXCHANGE,
        credibilityScore: 95,
        priority: 'P0',
        pollingInterval: 60, // 1m
        categories: ['CRYPTO', 'MEMECOIN'],
        watchTopics: [
            'listing',
            'spot listing',
            'futures listing',
            'perpetual',
            'asset support',
            'trading begins',
        ],
        requiresConfirmation: false,
        officialDomain: 'coinbase.com',
        rsshubRoute: '/twitter/user/CoinbaseMarkets',
    },
    {
        handle: 'Coinbase',
        displayName: 'Coinbase',
        enabled: true,
        sourceType: XSourceType.EXCHANGE,
        credibilityScore: 90,
        priority: 'P1',
        pollingInterval: 120, // 2m
        categories: ['CRYPTO'],
        watchTopics: ['crypto', 'announcement', 'web3'],
        requiresConfirmation: false,
        officialDomain: 'coinbase.com',
        rsshubRoute: '/twitter/user/Coinbase',
    },
    {
        handle: 'binance',
        displayName: 'Binance',
        enabled: true,
        sourceType: XSourceType.EXCHANGE,
        credibilityScore: 95,
        priority: 'P0',
        pollingInterval: 60, // 1m
        categories: ['CRYPTO', 'MEMECOIN'],
        watchTopics: [
            'listing',
            'delisting',
            'launchpool',
            'launchpad',
            'airdrop',
            'trading pair',
            'futures',
            'new token',
            'memecoin',
        ],
        requiresConfirmation: false,
        officialDomain: 'binance.com',
        rsshubRoute: '/twitter/user/binance',
    },
];
