import { XSourceType } from '../../types';
import type { PublicOfficialRole, XSource } from '../types';

export const GOVERNMENT_AND_MACRO_X_SOURCES: XSource[] = [
    {
        handle: 'federalreserve',
        displayName: 'Federal Reserve',
        enabled: true,
        sourceType: XSourceType.CENTRAL_BANK,
        credibilityScore: 100,
        priority: 'P0',
        pollingInterval: 60, // 1m
        categories: ['MACRO', 'MARKET'],
        watchTopics: [
            'interest rate',
            'FOMC',
            'Powell',
            'inflation',
            'liquidity',
            'balance sheet',
            'QT',
            'QE',
            'economic outlook',
            'banking',
            'monetary policy',
        ],
        requiresConfirmation: true,
        officialDomain: 'federalreserve.gov',
        rsshubRoute: '/twitter/user/federalreserve',
    },
    {
        handle: 'USTreasury',
        displayName: 'U.S. Department of the Treasury',
        enabled: true,
        sourceType: XSourceType.GOVERNMENT_AGENCY,
        credibilityScore: 100,
        priority: 'P0',
        pollingInterval: 60, // 1m
        categories: ['MACRO', 'REGULATION', 'CRYPTO'],
        watchTopics: [
            'Treasury',
            'sanctions',
            'OFAC',
            'stablecoin',
            'crypto sanctions',
            'digital assets',
            'Treasury yields',
            'liquidity',
            'debt',
            'financial regulation',
        ],
        requiresConfirmation: true,
        officialDomain: 'home.treasury.gov',
        rsshubRoute: '/twitter/user/USTreasury',
    },
    {
        handle: 'SECGov',
        displayName: 'U.S. Securities and Exchange Commission',
        enabled: true,
        sourceType: XSourceType.GOVERNMENT_AGENCY,
        credibilityScore: 100,
        priority: 'P0',
        pollingInterval: 60, // 1m
        categories: ['REGULATION', 'CRYPTO'],
        watchTopics: [
            'Bitcoin ETF',
            'Ethereum ETF',
            'crypto enforcement',
            'securities',
            'exchange',
            'token regulation',
            'ETF approval',
            'ETF rejection',
            'digital assets',
        ],
        requiresConfirmation: true,
        officialDomain: 'sec.gov',
        rsshubRoute: '/twitter/user/SECGov',
    },
    {
        handle: 'CFTC',
        displayName: 'Commodity Futures Trading Commission',
        enabled: true,
        sourceType: XSourceType.GOVERNMENT_AGENCY,
        credibilityScore: 100,
        priority: 'P0',
        pollingInterval: 60, // 1m
        categories: ['REGULATION', 'CRYPTO'],
        watchTopics: [
            'crypto derivatives',
            'Bitcoin',
            'Ethereum',
            'commodity',
            'futures',
            'perpetual',
            'exchange regulation',
            'digital assets',
        ],
        requiresConfirmation: true,
        officialDomain: 'cftc.gov',
        rsshubRoute: '/twitter/user/CFTC',
    },
    {
        handle: 'BLS_gov',
        displayName: 'Bureau of Labor Statistics',
        enabled: true,
        sourceType: XSourceType.GOVERNMENT_AGENCY,
        credibilityScore: 100,
        priority: 'P0',
        pollingInterval: 60, // 1m
        categories: ['MACRO', 'MARKET'],
        watchTopics: [
            'CPI',
            'PPI',
            'jobs',
            'NFP',
            'unemployment',
            'wages',
            'inflation',
            'employment',
        ],
        requiresConfirmation: true,
        officialDomain: 'bls.gov',
        rsshubRoute: '/twitter/user/BLS_gov',
    },
    {
        handle: 'WhiteHouse',
        displayName: 'The White House',
        enabled: true,
        sourceType: XSourceType.GOVERNMENT_INSTITUTION,
        credibilityScore: 100,
        priority: 'P0',
        pollingInterval: 60, // 1m
        categories: ['GOVERNMENT', 'MACRO', 'REGULATION'],
        watchTopics: [
            'crypto',
            'Bitcoin',
            'digital asset',
            'stablecoin',
            'tariff',
            'China',
            'sanctions',
            'trade',
            'banking',
            'Fed',
            'Treasury',
            'tax',
            'regulation',
            'executive order',
        ],
        requiresConfirmation: true,
        officialDomain: 'whitehouse.gov',
        rsshubRoute: '/twitter/user/WhiteHouse',
    },
    {
        handle: 'POTUS',
        displayName: 'President of the United States',
        enabled: true,
        sourceType: XSourceType.GOVERNMENT_INSTITUTION,
        credibilityScore: 100,
        priority: 'P0',
        pollingInterval: 60, // 1m
        categories: ['GOVERNMENT', 'MACRO', 'REGULATION'],
        watchTopics: [
            'crypto',
            'Bitcoin',
            'digital asset',
            'tariff',
            'sanctions',
            'executive order',
        ],
        requiresConfirmation: true,
        officialDomain: 'whitehouse.gov',
        rsshubRoute: '/twitter/user/POTUS',
    },
];

// Dynamic public officials role registry (not hardcoded to current officeholders permanently)
export const PUBLIC_OFFICIALS_ROLE_REGISTRY: PublicOfficialRole[] = [
    {
        role: 'PRESIDENT',
        handle: 'realDonaldTrump',
        name: 'Donald Trump',
        effectiveFrom: '2025-01-20',
        effectiveTo: null,
    },
];

export const PUBLIC_OFFICIALS_X_SOURCES: XSource[] = PUBLIC_OFFICIALS_ROLE_REGISTRY.map((official) => ({
    handle: official.handle,
    displayName: official.name,
    enabled: true,
    sourceType: XSourceType.PUBLIC_OFFICIAL,
    credibilityScore: 90,
    priority: 'P0',
    pollingInterval: 60,
    categories: ['MACRO', 'GOVERNMENT', 'CRYPTO'],
    watchTopics: ['crypto', 'Bitcoin', 'tariff', 'China', 'regulation', 'economy'],
    requiresConfirmation: false,
    role: official.role,
    effectiveFrom: official.effectiveFrom,
    effectiveTo: official.effectiveTo,
    rsshubRoute: `/twitter/user/${official.handle}`,
}));
